# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 21:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Main',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)', message='invalid e-mail')])),
                ('password', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('car_company', models.CharField(choices=[('MS', 'MARUTI_SUZUKI'), ('TY', 'TOYOTA'), ('HY', 'HYUNDAI'), ('HON', 'HONDA'), ('FT', 'FIAT'), ('VG', 'VOLKSWAGEN'), ('FD', 'FORD'), ('LX', 'LUXURY'), ('OTH', 'OTHERS')], db_index=True, default='OTH', max_length=50)),
                ('car_model', models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator('(^[1-9]+[0-9]+$)')])),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
